apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test-server
  name: test-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-server
  template:
    metadata:
      labels:
        app: test-server
    spec:
      containers:
      - image: nginx
        name: nginx
        resources:
          limits:
            cpu: 0.5
            memory: 128Mi

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: test-server
  name: test-server
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: test-server
  sessionAffinity: None
  type: ClusterIP

---

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: test-server
  labels:
    app: test-server
spec:
  backend:
    serviceName: test-server
    servicePort: 80
